branches:
    - master
    - auto
    - try

host:
    distro: fedora/25/cloud

packages:
    - gcc
    - sudo
    - which
    - attr
    - fuse
    - gjs
    - parallel
    - clang
    - libubsan
    - gnome-desktop-testing
    - pkgconfig(fuse)
    - pkgconfig(gio-unix-2.0)
    - pkgconfig(gobject-introspection-1.0) >= 1.40.0
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive) >= 2.8.0
    - pkgconfig(libelf) >= 0.8.12
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ostree-1) >= %{ostree_version}
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(libseccomp)
    - pkgconfig(xau)
    - bubblewrap >= %{bubblewrap_version}
    - docbook-dtds
    - docbook-style-xsl
    - intltool
    - libattr-devel
    - libcap-devel
    - libdwarf-devel
    - elfutils
    - systemd
    - ostree
    - gpgme-devel
    - /usr/bin/xmlto
    - /usr/bin/xsltproc
    - redhat-rpm-config
    - /usr/bin/update-mime-database
    - /usr/bin/update-desktop-database
    - /usr/bin/gtk-update-icon-cache

env:
    CFLAGS: '-fsanitize=undefined'

build:
    config-opts: >
      --prefix=/usr
      --libdir=/usr/lib64
      --enable-installed-tests
      --enable-gtk-doc

tests:
    - make check

timeout: 30m

artifacts:
    - test-suite.log

---

inherit: true

context: Clang

container:
    image: fedora:25

env:
    CC: 'clang'
    CFLAGS: '-Werror=unused-variable'

tests:
artifacts:
