#!/bin/sh

if [ x$2 != 'x--some-arg' ] ; then
	exit 2
fi

cat <<EOF > Makefile
all:
	echo Building
	if [ "x\$(CFLAGS)" != "x-O2 -g" ]; then exit 1; fi
	if [ "x\$(FOO)" != xbar ]; then exit 1; fi
	if [ "x\$(BAR)" != x2 ]; then exit 1; fi

install:
	echo Installing
	if [ "x\$(FOO)" != xbar ]; then exit 1; fi
	if [ "x\$(BAR)" != x3 ]; then exit 1; fi
	mkdir -p /app/bin
	cp -a hello2.sh /app/bin/
	mkdir -p /app/share
	cp -a app-data /app/share/
EOF
